// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/plugins/app@components/hello-world/hello-world.vue')['default']
    Home: typeof import('./src/plugins/app/home/home.vue')['default']
    IMajesticonsBadgeCheckLine: typeof import('virtual:vite-icons/majesticons/badge-check-line')['default']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
  }
}

export { }
